project:
  type: book
  output-dir: docs

book:
  title: "Probabilidade C"
  author: "James D Santos"
  date: "05/01/2026"
  chapters:
    - index.qmd
    - vetores_aleatorios_discretos.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
 